class Actividad {
  int idAct;
  set setIdAct(int value) => idAct =value;
  String titulo;
  set setTitulo(String value) => titulo = value;
  String descripcion;
  set setDescripcion(String value) => descripcion = value;
  String direccion;
  set setDireccion(String value) => direccion = value;
  String sexo;
  set setSexo(String value) => sexo = value;
  String description2;
  set setDescripcion2(String value) => description2 = value;
  String description3;
  set setDescripcion3(String value) => description3 = value;
  bool certOfic;
  set setCert(bool value) => certOfic = value;
  int edadMin;
  set setEdadMin(int value) => edadMin = value;
  int edadMax;
  set setEdadMax(int value) => edadMax = value;
  double price;
  set setPrice(double value) => price = value;
  int numParticipantes;
  set setParticipantes(int value) => numParticipantes = value;
  String horaStar;
  set setHoraS(String value) => horaStar = value;
  String  horaEnd;
  set setHoraE(String value) => horaEnd = value;
  bool tipoEspacion;
  set setEspacio(bool value) => tipoEspacion = value;
  bool cancelacion;
  set setCancelacion(bool value) => cancelacion = value;
  String video;
  set setVideo(String value) => video = value;
  int numSesion;
  set setSesion(int value) => numSesion = value;
  String foto;
  set setFoto(String value) => foto = value;
  double latitude;
  set setLatitude(double value) => latitude=value;
  double longitude;
  set setLongitude(double value) => latitude=value;
  int idLocalidades;
  set setLocalidad(int value) => idLocalidades = value;
  int idIdiomas;
  set setIdioma(int value) => idIdiomas = value;
  int idUser;
  set setUser(int value) => idUser = value;
  int idInteres;
  set setInteres(int value) => idInteres = value;
}
